name: Check Oasis Tickets

on:
  schedule:
    - cron: "0 * * * *" # Se ejecuta cada hora en el minuto 0
  workflow_dispatch: # Permite ejecutarlo manualmente desde GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pushbullet.py

      - name: Install Chrome
        run: |
          sudo apt update
          sudo apt install -y chromium-browser chromium-chromedriver

      - name: Run script
        env:
          PB_API_KEY: ${{ secrets.PB_API_KEY }}
        run: |
          python check_tickets.py
